; Parking Config file for all machine
; ** Reader type 0:none 1:Eltra 2:CRT350 3:MF700 4:Dispenser+MF700 6:MCP210+MF700
; ** Comport => 0:none 1:COM1 2:COM2 3:COM3 ....

# Test
[COMMON]
ParkingID=0                  ;; 停車場編號
ParkingName=Parktron         ;; Print in barcode Title , max: 30 charactor include space
ServerIP=192.168.0.182       ;; Server IP 位置
ServerPort=1792
DateTimeFormat=yyyy-mm-dd hh:nn:ss 
QuietTime=15                 ;; 未動作時間(秒)
;; For Barcode setting
;; g(2)p(8)d(6)t(4) + check sum(2)
;; d:date t:time g:GateID p:TicketID
;; p(2)a(1)l(0)s(1)d(4)t(4)n(8) *language取消不用
;; p:ParkingID a:AreaID l:Language s:status d:date t:time n:TicketID
Type=0                      ;;0:Easy Type   1:IPMS版
Palstn=dgpt                   ;;if Type == 1 then this Format string is palstn
DateFormat=mdy
Note=This is test Ticket!   ;; Print in barcode note , max: 50 charactor include space
Button_Timeout=10					;;等待按鈕時間,超過時間會發alarm給server,預設為10秒
TakeTicket_Timeout=10					;;等待取票時間,超過時間會發alarm給server,預設為10秒
CloseBarrier_Timeout=10					;;等待關門時間,超過時間會發alarm給server,預設為10秒
WaitCardIn_Timeout=10					;;等待插入票卡時間,超過時間會發alarm給server,預設為10秒

;; 1區設定
[Location01]
Name=一區					;;
FreeTime=1         			;; 進場免費時間 單位:分鐘
PaidTime=5         			;; 繳完費出場緩衝時間 單位:分鐘
Fee=10             			;; 每 計費單位 費率
FeeTime=1          			;; 計費單位 1:1小時 2:半小時 3:0.5小時,最低消費一小時 4:累進 5:計次(一天一次)
ParkingFullCanEntry=0   	;; 0:When Parking is Full,can't Get into Parking  1: When Parking is Full,can Get into Parking
SeasonCheckPlate=0          ;; 月票要不要檢查車牌
PaidTime=1         			;; 繳完費出場緩衝時間 單位:分鐘

;; 2區設定
[Location02]
Name=二區
FreeTime=1         		    ;; 進場免費時間 單位:分鐘
Fee=10             		    ;; 每 計費單位 費率
FeeTime=1          		    ;; 計費單位 1:1小時 2:半小時 3:0.5小時,最低消費一小時 4:累進 5:計次(一天一次)
SeasonCheckPlate=0          ;; 月票要不要檢查車牌
PaidTime=1         			;; 繳完費出場緩衝時間 單位:分鐘

;入口第一台
[IN01]
AreaID=1  				    ;; 區碼
MachineID=11  			    ;; 機號
ClientID=02010700           ;; (Hex) It is communication id 
PlateServerIP=192.168.0.182  ;; 車牌辨識Server IP 垃址
PlateServerPort=2393
PlateClientID=06010700      ;; (Hex) It is communication id
PlateTimeout=15             ;; 
HReaderPort=2 			    ;; Hourly Reader COM port
HReaderType=3 			    ;; Houly Reader Type
SReaderPort=0 			    ;; Season Reader COM port
SReaderType=0 			    ;; Season Reader Type
SeasonReadTag=0    		    ;; 1:月票卡只讀 TAG  0:月票卡讀票卡內容
AutoIssueTicket=0  		    ;; Auto Issue Ticket when loop1 detect 0:Dsable 1:Enable
DispenserQuantity=1 	    ;; 0:none 1:mifare card 2:Mifare Card x2
MifareDispenser=0  		    ;; Chip Coin/Mifare Dispenser COM port
EasyCardIOControl=1         ;; 悠遊卡用i/o控制 1:true 0:false
BinsSize=100                ;; 回收票箱容量
PreTicket=0                 ;; 預發卡 1:Yes 0:no

;入口第二台
[IN02]
AreaID=1
MachineID=13
ClientID=03010700       ;; (Hex) It is communication id
PlateServerIP=192.168.0.182  ;; 車牌辨識Server IP 垃址
PlateServerPort=2393
PlateTimeout=5
HReaderPort=2 			;; Hourly Reader Compport
HReaderType=3 			;; Houly Reader Type
SReaderPort=0 			;; Season Reader Comport
SReaderType=0 			;; Season Reader Type
SeasonReadTag=0    		;; 1:月票卡只讀 TAG  0:月票卡讀票卡內容
AutoIssueTicket=0  		;; Auto Issue Ticket when loop1 detect. 0:disable 1:enable
BinsSize=10             ;; 回收票箱容量
PreTicket=0             ;; 預發卡 1:Yes 0:no

;出口第一台
[OUT01]
AreaID=1
MachineID=12
ClientID=04010700       ;; (Hex) It is communication id
PlateServerIP=192.168.0.182  ;; 車牌辨識Server IP 垃址
PlateServerPort=2393
PlateClientID=06010700  ;; (Hex) It is communication id 
PlateTimeout=15
HReaderPort=2 			;; Hourly Reader Compport
HReaderType=3 			;; Houly Reader Type
SReaderPort=0 			;; Season Reader Comport
SReaderType=0 			;; Season Reader Type
MaxRetriev=500 			;; Max Retriev Ticket,Device will send message to server when Retriev Ticket bigger then this value .
MifareDispenser=0  		;; Chip Coin/Mifare Dispenser COM port
DispenserQuantity=1 	;; 0:none 1:chip coin  2:mifare card  3:Mifare Card x2
BinsSize=10             ;; 回收票箱容量

;; APS
[APS01]
AreaID=1
MachineID=12
HReaderPort=1 			;; Hourly Reader Compport
HReaderType=3 			;; Houly Reader Type
SReaderPort=0 			;; Season Reader Comport
SReaderType=0 			;; Season Reader Type