;%1b:MachineID; %1c:plate; %1d:date; %1e:Season/Value End date; %1n:ticketID; %1s:state; %1t:time; %1v:value; %1~:換行

[ticket_print_in]
狀態:%1s 卡號:%1n%1~進場時間:%1d%1t%1~遺失票卡需繳交工本費100元

[ticket_print_out]
狀態:%1s 卡號:%1n%1~出場時間:%1d%1t%1~

[month_print_in]
狀態:%1s 卡號:%1n%1~進場時間:%1d%1t%1~有效:%1e%1~

[month_print_out]
狀態:%1s 卡號:%1n%1~出場時間:%1d%1t%1~有效:%1e%1~

[value_print_in]
狀態:%1s 卡號:%1n%1~進場時間:%1d%1t%1~儲值:%1v%1~

[value_print_out]
狀態:%1s 卡號:%1n%1~出場時間:%1d%1t%1~儲值:%1v%1~
